---
title: "plots_md"
author: "Szymon Janowski"
date: "4 11 2020"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, error = FALSE
)
```

## Load libraries
```{r load_test, error=FALSE, warning=FALSE}
library(ggplot2)
library(cowplot)
library(dbplyr)
library(dplyr)
library(wesanderson)
library(tidyr)
library("RColorBrewer")
library(VGAM)
library(tibble)
library(ramify)
```


## Load data

```{r load}
df <- as.tibble(read.csv("results.csv"))
problems = unique(df$problem)
df <- df %>% arrange(problem_size)
df
```

## Score

<!-- # ```{r score2, fig.width=12, fig.height=6} -->
<!-- #  -->
<!-- # df_temp <- df %>% -->
<!-- #   select(c("problem", "optimizer", "final_score")) %>% -->
<!-- #   filter(problem != "pr1002" & problem != "pcb442") %>% -->
<!-- #   summarySE(measurevar="final_score", groupvars=c("optimizer","problem")) -->
<!-- #  -->
<!-- #    -->
<!-- # pd <- position_dodge(0.1) -->
<!-- #  -->
<!-- # plot_seen <- ggplot( -->
<!-- #     df_temp, -->
<!-- #     aes( -->
<!-- #      x = problem, -->
<!-- #      y = final_score, -->
<!-- #      color = optimizer, -->
<!-- #      group = optimizer -->
<!-- #     )) + geom_errorbar(aes(ymin=final_score-se, ymax=final_score+se), colour="black", width=.1, position=pd) + -->
<!-- #          geom_line(position=pd, alpha=0.4) + -->
<!-- #          geom_point(position=pd, size=3, shape=21, fill="white") + -->
<!-- #          theme_bw() -->
<!-- #  -->
<!-- # plot_seen -->
<!-- #  -->
<!-- # ``` -->

```{r score, fig.width=12, fig.height=6}

data_summary <- function(x) {
   m <- mean(x)
   ymin <- m-sd(x)
   ymax <- m+sd(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}

# boxi <- function(df_temp){
#   
#   # opti <- df_temp[df_temp$optimizer == "optimal",]$final_score
#   # dfi <- data.frame(problems, rep(opti, each=length(problems)))
#   
#   # p <- ggplot() +
#   #   geom_boxplot(
#   #     data = df_temp,
#   #     aes(
#   #       factor(optimizer),
#   #       final_score,
#   #       fill=optimizer)) +
#   #   # geom_line(data=dfi, aes(y=opti[1]), linetype="dotted", color="red") +
#   #   xlab("Optimizer") +
#   #   ylab("Score") +
#   #   theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
#   #   theme_bw()
#   
#   p <- ggplot(
#     data = df_temp,
#     aes(
#       factor(optimizer),
#       final_score,
#       fill=optimizer)) +
#     geom_violin(
#       trim=FALSE) +
#     # geom_line(data=dfi, aes(y=opti[1]), linetype="dotted", color="red") +
#     geom_boxplot(width=0.1, alpha=0.4) + 
#     xlab("Optimizer") +
#     scale_fill_brewer(palette="Blues") + theme_classic() +
#     theme_bw()
#     
#   return(p)
# }
# 
# for(p in problems){
#   df_temp_R <- df %>% filter(problem == p & (optimizer == "random" | optimizer == "random_walk")) %>% select(c("optimizer", "final_score"))
#   df_temp_nR <- df %>% filter(problem == p & (optimizer != "random" & optimizer != "random_walk")) %>% select(c("optimizer", "final_score"))
#   
#   p_boxplot_R <- boxi(df_temp_R)
#   
#   p_boxplot_nR <- boxi(df_temp_nR)
#   
#   p_comb <- plot_grid(p_boxplot_nR+ylab("Score"), p_boxplot_R+ylab(""), labels=c("1", "2"), nrow=1, ncol=2)
#   print(p_comb)
#   ggsave(sprintf("plots_res/alg_comp/violin/opt_comp_score_violin_%s.pdf", p), p_comb, width = 12, height = 6)
# }

# ggplot(data = df, aes(x=problem, y=final_score, fill=optimizer)) +
#   stat_summary(geom = "bar", fun.y = mean, position = "dodge") +
#   stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge", fun.args = list(mult = 100)) +
#   xlab("Optimizer") + ylab("Score") +
#   scale_fill_brewer(palette="Blues") +
#   theme_classic() +
#   theme_bw() +
#   scale_y_log10()

```

## Quality
```{r quality, fig.width=12, fig.height=5}

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

df_temp <- df %>%
  mutate(quality = normalize((optimal_cost-final_cost)/optimal_cost)) %>%
  # select(c("problem", "optimizer", "quality")) %>%
  # summarySE(measurevar="quality", groupvars=c("problem", "problem_size","optimizer")) #%>%
  group_by(problem, problem_size, optimizer) %>%
  top_n(n=1, wt=quality) #%>%
  # arrange(problem_size)

# print(df_temp)

# df_temp$quality <- normalize(df_temp$quality)

df_temp <- df_temp %>%
  filter(optimizer != "optimal")

# df_temp$sd <- df_temp$sd * 3

# print(df_temp)

# brewer.pal(n = 8, name = "Set3")

pd <- position_dodge(0.5)

t2.rect1 <- data.frame (xmin="greedy", xmax="heuristic", ymin=-Inf, ymax=Inf)

plot_comb <- ggplot(df_temp, aes(x=reorder(problem, problem_size), y=quality, colour=reorder(problem, problem_size), group=optimizer)) +

  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=0,xmax=1.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=2.5,xmax=3.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=4.5,xmax=5.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=6.5,xmax=7.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=8.5,xmax=9.5,inherit.aes = FALSE) +

  # geom_errorbar(aes(ymin=quality-sd, ymax=quality+sd), width=.7, position=pd, color="black", size=.1) +
  geom_point(color = "black", size = 3.2, position=pd) +
  geom_point(aes(color=optimizer), size=3, position=pd) +
  geom_line(aes(color=optimizer), linetype="dotdash", alpha=0.7, position=pd) +
  xlab("Problem") + ylab("Jakosc") +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  # theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1)) +
  # scale_y_log10() +
  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_comb

ggsave("plots_res/final/opt_comp_quality_best.pdf", plot_comb, width=12, height=5)

```


## Time

```{r time, fig.width=12, fig.height=5}

plots_vec <- vector('list', length(problems))

# i<-0
# for(p in problems){
#   df_temp <- df %>%
#     filter(problem == p) %>%
#     select(c("optimizer", "time_ms")) %>%
#     distinct(optimizer, time_ms, .keep_all = TRUE)
# 
#   df_temp$opt <- c("O", "S", "G", "H", "R", "RW")
# 
#   plot_ <- ggplot(
#     df_temp,
#     aes(
#       x=opt,
#       y=time_ms)) + geom_point(aes(col=time_ms), size=3) + xlab("Optimizer") + ylab("Time [ms]")
# 
#   i<-i+1
#   plots_vec[[i]] <- plot_
# }
# 
# plot_comb <- plot_grid(plotlist=plots_vec, nrow=4, ncol=3, labels=problems, align = 'hv', hjust=0, vjust=4, label_size=17, label_colour = "blue")
# plot_comb

df_temp <- df %>%
  filter(optimizer != "optimal") %>%
  transform(time_ms =  time_duration_ms/time_iterations) %>%
  # select(c("problem", "optimizer", "time_ms")) %>%
  distinct(optimizer, problem, problem_size, time_ms, .keep_all = TRUE)
  # summarySE(measurevar="time_ms", groupvars=c("problem","optimizer"))

# head(df_temp)

t2.rect1 <- data.frame (xmin="greedy", xmax="heuristic", ymin=0, ymax=Inf)

# reorder(problem, -problem_size)
# optimizer

pd <- position_dodge(0.5)

plot_comb <- ggplot(df_temp, aes(x=reorder(problem, problem_size), y=time_ms, colour=reorder(problem, -problem_size), group=optimizer)) +
  
  geom_point(color = "black", size = 3.2, position=pd) +
  geom_point(aes(color=optimizer), size=3, position=pd) +
  geom_line(aes(color=optimizer), linetype="dotdash", alpha=0.7, position=pd) +
  xlab("Problem") + ylab("Czas dzialania [ms]") +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  # theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1)) +
  scale_y_log10(label=scientific_10) +

  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=0,xmax=1.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=2.5,xmax=3.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=4.5,xmax=5.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=6.5,xmax=7.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=8.5,xmax=9.5,inherit.aes = FALSE) +

  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_comb

ggsave("plots_res/final/opt_comp_time.pdf", plot_comb, width=12, height=5)
```

## Efketywnosc w czasie

```{r efwcz, fig.width=7, fig.height=4}

df_temp <- df %>%
  # filter(problem != "pr1002" | problem != "pcb442") %>%
  transform(time_ms =  time_duration_ms/time_iterations) %>%
  mutate(quality = normalize((optimal_cost-final_cost)/optimal_cost)) %>%
  summarySE(measurevar="quality", groupvars=c("problem", "problem_size","optimizer", "time_ms")) %>%
  select(c("problem", "problem_size", "quality", "optimizer", "time_ms")) %>%
  arrange(problem_size)

# df_temp$quality <- normalize(df_temp$quality)

# head(df_temp)

scientific_10 <- function(x) {
  parse(text=gsub("e", " %*% 10^", scales::scientific_format()(x)))
}

plot_steps <- ggplot(df_temp, aes(time_ms, quality, color=optimizer)) +
  geom_jitter(alpha=0.8, size=2, position=position_jitterdodge()) +
  xlab("Czas dzialania [ms]") +
  ylab("Jakosc") +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  # scale_y_log10() +
  scale_x_log10(label=scientific_10) +
  # theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)) +
  # scale_x_continuous(label=scientific_10)

  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_steps

ggsave("plots_res/final/opt_comp_qual_time.pdf", plot_steps, width=7, height=5)

```

## Steps

```{r steps, fig.width=7, fig.height=5}

# df_temp <- df %>% select(c("problem", "optimizer", "steps")) %>% filter(optimizer == "steepest" | optimizer == "greedy")
# # df_temp$optimizer <- toupper(substr(df_temp$optimizer, 0, 1))
# 
# plot_steps <- ggplot(
#     df_temp,
#     aes(
#       factor(optimizer),
#       steps,
#       fill=optimizer)) +
#   geom_boxplot(size=0.1) + xlab("Optimizer") + ylab("Steps") + facet_wrap(~problem, scales="free_y") +
#   theme_bw(
#     base_line_size = 1/10,
#     base_rect_size = 1/10
#   ) +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#   scale_y_log10()
# 
# plot_steps

pd <- position_dodge(0.1)

df_temp <- df %>%
  # select(c("problem", "optimizer", "steps")) %>%
  filter(optimizer == "steepest" | optimizer == "greedy") %>%
  summarySE(measurevar="steps", groupvars=c("problem", "problem_size","optimizer")) %>%
  arrange(problem_size)

df_temp$optimizer <- toupper(substr(df_temp$optimizer, 0, 1))
df_temp$sd <- df_temp$sd * 3

# head(df_temp)

plot_comb <- ggplot(df_temp, aes(x=reorder(problem, problem_size), y=steps, colour=optimizer, group=optimizer)) +
  geom_errorbar(aes(ymin=steps-sd, ymax=steps+sd), width=.7, position=pd, color="black") +
  geom_line(position=pd, linetype="dotdash", alpha=0.7) +
  geom_point(position=pd, color = "black", size = 3.2) +
  geom_point(aes(color=optimizer), size=3, position=pd) +
  xlab("Problem") + ylab("Liczba krokow") +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1)) +
  scale_y_log10(label=scientific_10) +
  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_comb

ggsave("plots_res/final/opt_comp_steps.pdf", plot_comb, width=7, height=5)

```

## Seen

```{r sse}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```

```{r seen, fig.width=8, fig.height=5}

df_temp <- df %>%
  select(c("problem", "problem_size", "optimizer", "seen_solutions")) %>%
  filter(optimizer != "optimal") %>%
  summarySE(measurevar="seen_solutions", groupvars=c("problem", "problem_size","optimizer"))

pd <- position_dodge(0.5)

plot_comb <- ggplot(df_temp, aes(x=reorder(problem, problem_size), y=seen_solutions, colour=reorder(problem, problem_size), group=optimizer)) +

  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=0,xmax=1.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=2.5,xmax=3.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=4.5,xmax=5.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=6.5,xmax=7.5,inherit.aes = FALSE) +
  geom_rect(data=t2.rect1,aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),fill="black",alpha=0.1,xmin=8.5,xmax=9.5,inherit.aes = FALSE) +

  geom_errorbar(aes(ymin=seen_solutions-sd, ymax=seen_solutions+sd), width=.7, position=pd, color="black", size=.1) +
  geom_point(color = "black", size = 3.2, position=pd) +
  geom_point(aes(color=optimizer), size=3, position=pd) +
  geom_line(aes(color=optimizer), linetype="dotdash", alpha=0.7, position=pd) +
  xlab("Algorytm") + ylab("Liczba ocenionych rozwiazan") +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  # theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1)) +
  scale_y_log10(label=scientific_10) +
  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_comb

# plot_steps <- ggplot(
#     df_temp,
#     aes(
#       factor(optimizer),
#       seen_solutions,
#       fill=optimizer)) + geom_boxplot(size=0.1) + xlab("Optimizer") + ylab("Seen solutions") + facet_wrap(~problem, scales="free_y") +
#   theme_bw(
#     base_line_size = 1/10,
#     base_rect_size = 1/10
#   ) +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
# 
# plot_steps

ggsave("plots_res/final/opt_comp_seen.pdf", plot_comb, width=12, height=8)

```

## Jakosc pocz vs koncowa

```{r pk2, fig.width=12, fig.height=8}

# selected_problems = setdiff(problems, c("kroA100", "kroC100"))

df_temp <- df %>%
  # filter(problem %in% selected_problems) %>%
  filter(optimizer == "steepest" | optimizer == "greedy") %>%
  select(c("problem", "problem_size", "optimizer", "start_cost", "final_cost"))

for(p in problems){
  df_temp_temp <- df_temp %>%
    filter(problem == p)
  corr = cor(df_temp_temp$start_cost, df_temp_temp$final_cost, method="pearson")
  print(sprintf("Problem: %s | Corr: %s", p, corr))
}
```

```{r pk, fig.width=10, fig.height=8}

# selected_problems = setdiff(problems, c("kroA100", "kroC100"))


df_temp <- df %>%
  filter(problem != "pcb442" & problem != "pr1002" ) %>%
  # filter(problem %in% selected_problems) %>%
  mutate(final_quality = normalize((optimal_cost-final_cost)/optimal_cost)) %>%
  mutate(start_quality = normalize((optimal_cost-start_cost)/optimal_cost)) %>%
  filter(optimizer == "steepest" | optimizer == "greedy") %>%
  select(c("problem", "problem_size", "optimizer", "start_quality", "final_quality"))

# colnames(df_temp)
# 
# facetlims = df_temp %>% 
#   group_by(problem) %>% 
#   summarise(min = min(start_quality, final_quality), max = max(start_quality, final_quality)) %>%
#   gather(range, start_quality, -problem) %>%
#   mutate(final_quality = start_quality, range = NULL)

plot_steps <- ggplot(df_temp, aes(start_quality, final_quality, color=optimizer)) +
  geom_jitter(alpha=0.5) +
  xlab("Jakosc poczatkowa") +
  ylab("Jakosc koncowa") +
  
  facet_wrap(~reorder(problem, problem_size), scales="free") + 
  # geom_blank(data = facetlims) +
  theme_bw(
    base_line_size = 1/10,
    base_rect_size = 1/10
  ) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)) +
  labs(color='Algorytm') +
  scale_color_brewer(palette="Set2")

plot_steps

ggsave("plots_res/final/start_vs_end.pdf", plot_steps, width=10, height=8)

```


## Jakosc w czasie

```{r pk, fig.width=10, fig.height=7}


get_vs <- function(df){
  rows = nrow(df)

  vmin <- rep(0, rows)
  vmean <- rep(0, rows)
  v <- as.numeric(df$quality)
  
  for(i in seq_along(v)){
    vmin[i] <- max(v[1:i])
    vmean[i] <- mean(v[1:i])
  }
  
  df$vmin = vmin
  df$vmean = vmean
  df$iters = seq_along(v)
  
  return(df)
}

for(p in problems){
  df_temp <- df %>%
    filter(problem == p) %>%
    mutate(quality = normalize((optimal_cost-final_cost)/optimal_cost)) %>%
    select(c("problem", "optimizer", "quality"))
  
  # df_temp$quality <- normalize(df_temp$quality)
  
  df_temp_S <- df_temp %>%
    filter(optimizer == "steepest")

  df_temp_G <- df_temp %>%
    filter(optimizer == "greedy")

  df_temp_S <- get_vs(df_temp_S)
  df_temp_G <- get_vs(df_temp_G)
  
  df_temp <- rbind(df_temp_S, df_temp_G)
  
  colors <- c("Maksymalna" = '#F8766D', "Srednia" = '#00BFC4')

  plot_temp <- ggplot(df_temp) +
    geom_point(aes(x=iters, y=vmin, color='Maksymalna')) +
    geom_line(aes(x=iters, y=vmin, color='Maksymalna'), alpha=0.5) +
    geom_point(aes(x=iters, y=vmean, color='Srednia')) +
    geom_line(aes(x=iters, y=vmean, color='Srednia'), alpha=0.5) +
    labs(x = "Iteracja",
         y = "Jakosc",
         color = "Legenda wartosci") +
    scale_color_manual(values = colors) +
    ylim(c(NA, 1)) +
    facet_wrap(~optimizer, ncol=1) +
    theme_bw(
      base_line_size = 1/10,
      base_rect_size = 1/10
    ) +
  scale_color_brewer(palette="Set2")

  print(plot_temp)
  
  ggsave(sprintf("plots_res/final/all_mean_min/mean_min_score_%s.pdf", p), plot_temp, width = 8, height = 4)
}

```

## 5

```{r pk5, fig.width=8, fig.height=4}

parse <- function(x){
  sapply(x, function(x){
    stri <- strsplit(x, " ")
    x <- as.numeric(stri[[1]])
    id_x <- match(0, x)
    left <- x[1:id_x-1]
    right <- x[id_x:length(x)]
    vec <- c(right, left)
    return(vec[!is.na(vec)])
  })
}

for(p in problems){
  df_temp <- df %>%
    filter(optimizer != "optimal") %>%
    filter(problem == p) %>%
    mutate(quality = normalize((optimal_cost-final_cost)/optimal_cost)) %>%
    mutate(similarity = kendall.tau(parse(final_path), parse(optimal_path))) %>%
    # mutate(similarity = simi(parse(final_path), parse(optimal_path))) %>%
    select(c("problem", "optimizer", "quality", "similarity"))


  plot_temp <- ggplot(df_temp, aes(x=quality, y=similarity, color=optimizer)) +
    geom_jitter(alpha=0.6) +
    xlab("Jakosc") +
    ylab("Podobienstwo") +
    theme_bw(
      base_line_size = 1/10,
      base_rect_size = 1/10
    ) +
    labs(color='Algorytm') +
    scale_color_brewer(palette="Set2")

  print(plot_temp)

  ggsave(sprintf("plots_res/final/5/ex5_%s.pdf", p), plot_temp, width = 8, height = 4)

}

```









